language: clojure

jdk:
- openjdk8

services:
  - docker

sudo: required

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: TEth/cw4uzA8aGxA4l0Au5CUtSouTygq+iGFvgqVSdmIKsM0j6mQJ/RDGRyERF51D0AQ5X3bRTbnRfJueGowyoKFv62n47PskQ6hrr3XE3hsarOaWalqOYAzHJe2MO01wP/1fes6AhRqZgwC8rTktWj2PAPQIzuyBtH/BNV7JO/4AqmiRe/gb+Ii0JvQcZ/SJc4DNGMw6mqnQF+yzYXa8hOIFpWf0s/KPGTg6O7gQdE6rz7kzpknfn5lR0/d5hh6ixFpc5rZqEuDeP+EA7EFSJK9Sn4WGk1MBW+x9gA487Pj3/wddrAKl5O1BEx9Y3diOKAkXZE3n5zJWjmdfNsBFZqtLcCPV3bnJ6H3JxXpBG9fm8wWoXuz2BwKqUe3M33aHFyq4RUt5tDgv597JpGfoCqqsYQRGOXVybD3kdFdjvSY64NngyfFN83hgA1DyMrOQvI6M/bQzI1xDFt+zUYC0ip9/yn96WYDzYpC5QsjuKf9BoUESjH0/NHbxaDQ+2GsBmZhR//zeQwcN4de3gKc4tvYkP/D3QhMeSFRgq873mCbLlTck76qFahqjfMDz4woFY/1C461/nR8qv9RI2S+BBzd8RRg85fiSmHGHZWSmMOOx2wdy4pumux98TnGrYIJukEB5h/S/4aZbkvMpu9mLF/lol/N2rVFNv6nHOaQWGo= # DOCKER_USER
  - secure: KwM2J/HxxvAXAu91m1im/v0o0volV75o1xzE2nX1Nx2k2zyoYT8B6HiHa2EGuEsZX2smyoLRK+IDbY2znSt0FV+Z0C8SS5y7N6KFTRfyxqVr1Fl0yb6FfonRN9HYbBtx0FQmfoBGTNiFOb38BR5qGxv4fuqFJo0YMC3Hb38ElSwQb2LnYEsO5m5jfGN8U999K7P1kGLRmbWVx4FCMLgvUITLJYUnYHIbVoPVzL8HXAqtF9oXlsOoXHQMEUEVg52aiuONXyWMvAmzo5Gyne9aGROO8HyXxnKRx4rukwnOLQk6v5rupKSnCwuIRcovDtFr6WE1e8JlKtodELwGriyk5pAbUoCAD3aUXsQ4QrUHvfkWUsMDFdD4IS7Dd5ELzKF17NYzLJpYrpcYiQXYtE7o8TUYimzpu5P4VJQX6QplOXPPl5R+cMpGGHDYAZnlon36dnsZKacrYoYSjCLlFMvpbEu+U8s7mCZ/WMNq1lPf0uJDAQqvqDY5XNP7J/3sZl6KSaerd2dc7GnJLCljalv5sz4nZFgLb4TITtYINI9Opghsu94GIMGefi4DtZYeocjP30apEVuilp+aLCS/e/pkLgVpZf1yDj9KLuCSm0obnqXgsO7v5am/qzid7ps77m+72wtm9wpD5SdYzTqpf/6hzCUJpWXPzRu018ZexcjRJUw= # DOCKER_PASS

before_install:
  # - cd test/resources
  # vm.max_map_count=262144 is needed so elasticsearch 5 will start.
  # Defaults are too low.
  - sudo sysctl -w vm.max_map_count=262144
  #- docker-compose up -d
  - make docker-deps-up
  # - cd ../..
  - sudo apt-add-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install libgdal-dev libgdal-java -y

after_success:
  - bin/deploy
  - make docker-deps-down

notifications:
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
